name: CI

on:

  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  CI:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Setup do NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2

      - name: Instalacao do Mocha e pacotes para testes
        run: |
          cd src;
          npm install -g mocha;
          npm install;
          
      - name: Execucao dos testes
        run: mocha src/test/convert.js
        
      - name: Autenticacao no DockerHub
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Construcao da imagem Docker
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            thedfsc/aula-conversao-temperatura:v1
            thedfsc/aula-conversao-temperatura:latest
      
        
